/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nodeshpa' at '2/13/18 12:12 PM' with Gradle 2.13
 *
 * @author nodeshpa, @date 2/13/18 12:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
